version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongo_db
    restart: always
    env_file:
      - ./.env
    ports:
      - 27018:27017
    volumes:
      - ./Docker/monogdb:/docker/mongodb  
    networks:
      - webapp
  redis:
    image: redis:6.2.6-alpine
    command: 'redis-server --appendonly yes'
    restart: 'unless-stopped'
    ports:
      - 6379:6379
    volumes:
      - ./Docker/redisdb:/docker/redisdb 
    networks:
      - webapp    

  webapp:
    build: .
    depends_on:
      - mongodb
      - redis
    ports:
      - "5000:5000"
    env_file:
      ./.env
    networks:
      - webapp

volumes:
  mongodb:
networks:
  webapp:
    driver: bridge